### ISSUE TITLE
Update `@zetachain/toolkit` for Athens 3

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/toolkit#11]
```[tasklist]
### Hardhat tasks
- [x] account
- [x] balances (blocked on `@zetachain/protocol-contracts` [published](https://github.com/zeta-chain/protocol-contracts/issues/38), currently works with `yarn link`)
- [ ] faucet (blocked on https://linear.app/zetablockchain/issue/PD-3743/update-cli-faucet-to-work-with-athens-3)
```
```[tasklist]
### npm
- [x] Publish a temporary `@zetachain/toolkit@athens3` package
- [ ] Publish a stable package
```

Related PR: https://github.com/zeta-chain/toolkit/pull/10
```[tasklist]
### Tasks
- [x] Update to use `@zetachain/networks@athens3`
```
